using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ApprovedMedicalSurvey.UI
{
    public partial class FlatLightTheme : Form
    {
        public FlatLightTheme()
        {
            InitializeComponent();
        }

        private void close(object sender, EventArgs e)
        {
            Close();

        }

        private void FlatDarkTheme_Load(object sender, EventArgs e)
        {
            Scans f = new Scans();
            f.MdiParent = this;
            f.Show();
            f.Dock = DockStyle.Fill;
        }

        private void lookUpEdit3_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void panel9_Paint(object sender, PaintEventArgs e)
        {

        }

        private void panel6_Paint(object sender, PaintEventArgs e)
        {

        }

        private void button2_Click(object sender, EventArgs e)
        {

        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
            this.Close();
        }





      

        // This event is generated by Data Source Configuration Wizard
       

        // This event is generated by Data Source Configuration Wizard
       

      
    }
}